### ISSUE TITLE
Readme improve

### ISSUE THREAD

**Issue by gandb** [MaxPat931/Macros#3]
I like some scripts but I dont know how use it. Can explain in the read me file, some like quick start? Congratulation for the project.

PS: Specially WS-HideUnidentified.js

**Comment by MaxPat931** [comment]
Hey there, glad you found something here useful! 
However, as the current readme kinda outlines, I dont really know what I'm doing with JavaScript too much 😅, so this is really just a place I store things that I've hacked together from other resources (like searching existing macros in the Foundry Discord's #macro-polo channel) or that I've had written for me. 

Feel free to let me know which script you're having trouble with, or reach out to me on Discord (@max.pat) if you have any specific questions

**Comment by MaxPat931** [comment]
Whoops I think I declined you friend request, didnt realize it was you, you're not even in the foundry discord? haha

**Comment by gandb** [comment]
No problem, I will  send again =)

Best Rigards,

Cumprimentos,
*Edson Vicente Carli Junior*
